### PR TITLE
Foulgrid - grid based instrument based on foulplay

### PR DESCRIPTION
**Pull request by junklight**
I've added grid support to the foulplay script 

I have pisound/rpi/push2 based setup so not been tested on official hardware

### CODE REVIEW

**Comment by pq** [comment]
cool stuff.  if this just adds grid support, it would probably be better to add it `foulplay` itself...  unless you considered that?

/cc @notjustmat

**Comment by notjustmat** [comment]
I was just looking at this. I agree with @pq, in that it should probably just be added to ``foulplay``.

**Comment by junklight** [comment]
the reason I made it separate is that there is discussion on lines about using Norns without the grid and the play fair variants get mention there. 

It should be ok with no grid plugged in but I have no way of testing that. But if that works then  happy to merge it into foulplay.....

**Comment by junklight** [comment]
ok - do I make a PR to your repo? or do you want to do the merge? (my git skills are pretty basic)

**Comment by notjustmat** [comment]
I am preparing a PR from my repo now, so why not submit it there. That way I can test it on hardware and make sure that it still works sans grid before it gets into monome/dust.

**Comment by junklight** [comment]
ah ok - your script is a bit ahead of where I forked - got a few meetings now - might not get to this until wednesday......

**Comment by notjustmat** [comment]
No worries!

**Comment by junklight** [comment]
ok 

https://github.com/notjustmat/dust/pull/1

**Pull request closed without merging**
