### PR TITLE
Fix study 1 

### PR DESCRIPTION
**Pull request by okyeron**
per https://llllllll.co/t/norns-help/14016/679

Update to study 1 to fix screen issue

### CODE REVIEW

**Comment by okyeron** [comment]
Ack! sorry about those old commits - not sure how to remove those.

**Comment by catfact** [comment]
eh, don't worry about merge commits (they don't show in the diff)

**Comment by tehn** [comment]
i'll merge this for now, but FYI the bug is fixed in master and this is not required. i will remove this merge once the update is released.

**Comment by okyeron** [comment]
Oh cool. Didn't realize that was going to be a moot situation with the next update.

I was chatting with another user and they mentioned having problems with the study, and it looked like a quick fix.

**Pull request merged**
