### PR TITLE
jah/step script improvements

### PR DESCRIPTION
**Pull request by antonhornquist**
improvements:
- support for 99 patterns, persisted to disk in `data/jah/step.data` like `playfair`. new "pattern" param added, patterns are now practically saved/restored with pset albeit in another file.
- removed "grid width" param. script now uses actual width of connected grid
- added "cut quant" yes/no param that determine whether to quantize play position cutting to 1 step or not. before this playpos position was always quantized. unquantized cutting is more responsive.

fixes:
- removed unused code written for future param lock support. may revisit this later.

### CODE REVIEW

**Comment by okyeron** [comment]
not sure this is the right place to comment, but I've been having some problems with the `step` script not "letting go" of a grid device. If I load another script after `step`, my button presses do not work. I then need to ./stop.sh and ./start.sh norns to get the grid working properly again.

I have a DIY grid I'm working on so it's possible this is a bug on my end, but `step` is the only script that does this. I started rewriting the grid code in step to see if I could remedy this.

seems like `function Grid.add(dev)` here is a bit different from other scripts using a grid and is perhaps not necessary?

**Comment by antonhornquist** [comment]
@okyeron Earlier I experienced similar issues too, intermittently, but I have not been able to narrow it down. If you do, and can recreate this please create a new github issue detailing the necessary steps taken to recreate the issue.

The reason `Grid.add` is different is I wanted a UI notification for whether a grid was available or not. I've tried to cater for multiple devices (only first device connected is utilized), and I'm not using `g` and `gridkey` global functions.

**Comment by tehn** [comment]
i'm pretty sure _not_ using `g` might break inter-script grid usability.

but fear not, i'm about to rewrite the grid lua layer, so any scripts using `g` will need an update (for much greater readability)

**Comment by okyeron** [comment]
@antonhornquist This happens pretty much every time I use `step`.

(from the maiden interface)
1. load `step` - change some steps
2. load `awake` - grid keys will not do anything (no led feedback, no presses register)
3. unplug grid - maiden displays `dev_delete(): removing device 0`
4. plug grid back in - the pattern from `step' shows up on grid. Buttons change led states, but do not affect awake still playing from before.
5. stop and start of norns gets the grid working again.

It seems the grid device is not being deleted/removed when switching to another script or when unplugged/plugged? FWIW I get no feedback in maiden when running `step` and plugging in my grid. On unplugging, it shows `dev_delete(): removing device 1`

Could this be an issue with `Grid` being required/setup as `local` and not `global`?

**Comment by scanner-darkly** [comment]
i have a feeling this might be related to some of the issues i saw when trying to add arc support. looking forward to the fix!

**Comment by catfact** [comment]
> it's a serious flaw in the design of the grid system

i assume you refer to the way `g` and `gridkey` globals are used, and not the grid module itself.

if the former - i agree. if the latter - can't say i do.

defining `Grid.add` as in `step` was the idea when the grid module was written - its an assignable callback layer over the hardcoded handler layer (`norns.grid`). 

the use of `g` and `gridkey` in `startup.lua` just adds another layer of redirection, with no benefit that i can see since its still just a single callback that can't be chained or anything. but it also means that using the grid module as originally intended will break everything. if this is what you want, just get rid of the assignable callback in Grid.

**Comment by tehn** [comment]
@catfact yes, i meant the globals! the module itself is great.

i'm changing the grid system to emulate how the new midi system works, which seems to make a lot of sense in terms of usability and scripting.

**Comment by catfact** [comment]
@okyeron 
> FWIW I get no feedback in maiden when running step and plugging in my grid. On unplugging, it shows dev_delete(): removing device 1

this is just a debug print hanging around in device.c 
https://github.com/monome/norns/blob/master/matron/src/device/device.c#L61

> Could this be an issue with Grid being required/setup as local and not global?

i don't think so

**Comment by antonhornquist** [comment]
@okyeron 

> load `step` - change some steps
> load `awake` - grid keys will not do anything (no led feedback, no presses register)
> unplug grid - maiden displays `dev_delete(): removing device 0`
> plug grid back in - the pattern from `step' shows up on grid. Buttons change led states, but do not affect awake still playing from before.

Thanks - based on this I too can recreate issues using `step` and then switching to `awake`. I'll revisit this after the upcoming midi/grid/device changes are done and create a github issue if the issue is not resolved.

**Pull request merged**
