### PR TITLE
add pitch bend range param

### PR DESCRIPTION
**Pull request by pq**
not at all sure if this is the right way to go about this (or if it's even generally desired) but useful for me...

no hard feelings either way!

/cc @markwheeler

### CODE REVIEW

**Comment by tehn** [comment]
love the 48 note pitchbend!!

wondering if range should simply be a number instead of an option, ie, perhaps people want a bend range of some arbitrary semitone between 3 and 12?

**Comment by markwheeler** [comment]
Cool, yep agree a number 1-48 with default of 2 probably makes the most sense and perhaps renaming to 'Pitch Bend Range' for clarity? Thanks!

**Comment by pq** [comment]
fwiw: updated but untested.

will check out on device in a bit...

**Comment by pq** [comment]
cool.  thanks!

**Pull request merged**
