### PR TITLE
Animated graphics for earthsea script

### PR DESCRIPTION
**Pull request by markwheeler**
I added some animated ripple animations to earthsea, inspired by the graphics already in there. You'll see them on the play screen when notes are triggered, and a few animate at startup just to show the script is active.

If this goes against existing plans for earthsea then no worries, just thought I'd share.

It runs at 15fps as there seems to be a hard limit that doesn't allow the screen to update any faster, presumably this is by design to keep cpu usage in check?

### CODE REVIEW

**Comment by markwheeler** [comment]
sounds good! yep give me a shout come the time and i can split the vis off into another app or whatever makes sense

**Comment by pq** [comment]
hot stuff! 🔥 

> sounds good! yep give me a shout come the time and i can split the vis off into another app or whatever makes sense

aside: it'd be great to see some of these vis bits moving towards a reusable module.

**Comment by markwheeler** [comment]
Totally, I think I'm going to have a go at drafting up some more practical graph-style UI this week as generalized objects, see how that goes, and then we can all chat more about where that should live, how it should be structured etc 👍

**Comment by pq** [comment]
fantastic!  keen to see what you come up with.

**Pull request merged**
